// Package client provides primitives to interact the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package client

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"io/ioutil"
	"net/http"
	"net/url"
	"strings"
)

// Filters defines model for Filters.
type Filters struct {
	Country *string `json:"country,omitempty"`
	State   *string `json:"state,omitempty"`
}

// PhoneNumber defines model for PhoneNumber.
type PhoneNumber struct {
	CustomerName *string `json:"customerName,omitempty"`
	Number       *string `json:"number,omitempty"`
}

// PhoneNumbersResponseData defines model for PhoneNumbersResponseData.
type PhoneNumbersResponseData struct {
	Code            string        `json:"code"`
	Country         string        `json:"country"`
	NotValidNumbers []PhoneNumber `json:"notValidNumbers"`
	ValidNumbers    []PhoneNumber `json:"validNumbers"`
}

// QueryResponse defines model for QueryResponse.
type QueryResponse struct {
	Count *float32                   `json:"count,omitempty"`
	Data  []PhoneNumbersResponseData `json:"data"`
	Limit *int                       `json:"limit,omitempty"`
	Page  *int                       `json:"page,omitempty"`
}

// GetPhoneNumbersJSONBody defines parameters for GetPhoneNumbers.
type GetPhoneNumbersJSONBody Filters

// GetPhoneNumbersJSONRequestBody defines body for GetPhoneNumbers for application/json ContentType.
type GetPhoneNumbersJSONRequestBody GetPhoneNumbersJSONBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = http.DefaultClient
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetPhoneNumbers request  with any body
	GetPhoneNumbersWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	GetPhoneNumbers(ctx context.Context, body GetPhoneNumbersJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetPhoneNumbersWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetPhoneNumbersRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetPhoneNumbers(ctx context.Context, body GetPhoneNumbersJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetPhoneNumbersRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetPhoneNumbersRequest calls the generic GetPhoneNumbers builder with application/json body
func NewGetPhoneNumbersRequest(server string, body GetPhoneNumbersJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewGetPhoneNumbersRequestWithBody(server, "application/json", bodyReader)
}

// NewGetPhoneNumbersRequestWithBody generates requests for GetPhoneNumbers with any type of body
func NewGetPhoneNumbersRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	queryUrl, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	basePath := fmt.Sprintf("/phoneNumbers")
	if basePath[0] == '/' {
		basePath = basePath[1:]
	}

	queryUrl, err = queryUrl.Parse(basePath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryUrl.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	req = req.WithContext(ctx)
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetPhoneNumbers request  with any body
	GetPhoneNumbersWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader) (*GetPhoneNumbersResponse, error)

	GetPhoneNumbersWithResponse(ctx context.Context, body GetPhoneNumbersJSONRequestBody) (*GetPhoneNumbersResponse, error)
}

type GetPhoneNumbersResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *QueryResponse
}

// Status returns HTTPResponse.Status
func (r GetPhoneNumbersResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetPhoneNumbersResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetPhoneNumbersWithBodyWithResponse request with arbitrary body returning *GetPhoneNumbersResponse
func (c *ClientWithResponses) GetPhoneNumbersWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader) (*GetPhoneNumbersResponse, error) {
	rsp, err := c.GetPhoneNumbersWithBody(ctx, contentType, body)
	if err != nil {
		return nil, err
	}
	return ParseGetPhoneNumbersResponse(rsp)
}

func (c *ClientWithResponses) GetPhoneNumbersWithResponse(ctx context.Context, body GetPhoneNumbersJSONRequestBody) (*GetPhoneNumbersResponse, error) {
	rsp, err := c.GetPhoneNumbers(ctx, body)
	if err != nil {
		return nil, err
	}
	return ParseGetPhoneNumbersResponse(rsp)
}

// ParseGetPhoneNumbersResponse parses an HTTP response from a GetPhoneNumbersWithResponse call
func ParseGetPhoneNumbersResponse(rsp *http.Response) (*GetPhoneNumbersResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer rsp.Body.Close()
	if err != nil {
		return nil, err
	}

	response := &GetPhoneNumbersResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest QueryResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

