// Package api provides primitives to interact the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package api

import (
	"net/http"

	"github.com/go-chi/chi"
)

// GeoLocation defines model for GeoLocation.
type GeoLocation struct {
	City        *string  `json:"city,omitempty"`
	Country     *string  `json:"country,omitempty"`
	CountryCode *string  `json:"countryCode,omitempty"`
	IpAddress   *string  `json:"ipAddress,omitempty"`
	Latitude    *float32 `json:"latitude,omitempty"`
	Longitude   *float32 `json:"longitude,omitempty"`
}

// GeoLocationRequestData defines model for GeoLocationRequestData.
type GeoLocationRequestData struct {
	IpAddress *string `json:"ipAddress,omitempty"`
}

// GeoLocationResponseData defines model for GeoLocationResponseData.
type GeoLocationResponseData struct {
	Locations []GeoLocation `json:"locations"`
}

// GetLocationsJSONBody defines parameters for GetLocations.
type GetLocationsJSONBody GeoLocationRequestData

// GetLocationsJSONRequestBody defines body for GetLocations for application/json ContentType.
type GetLocationsJSONRequestBody GetLocationsJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get all locations by id address
	// (POST /locations)
	GetLocations(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
}

type MiddlewareFunc func(http.HandlerFunc) http.HandlerFunc

// GetLocations operation middleware
func (siw *ServerInterfaceWrapper) GetLocations(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLocations(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL     string
	BaseRouter  chi.Router
	Middlewares []MiddlewareFunc
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/locations", wrapper.GetLocations)
	})

	return r
}

